contact_links:
  - name: PolkaPox
    url: https://github.com/CDCgov/polkapox
    about: Please use the templates to post any issues of feature requests 
templates:
  # Template for bug reports
  - bug_report:
    file: bug_report.md
    labels: [bug]
  # Template for feature requests
  - feature_request:
    file: feature_request.md
    labels: [enhancement]
  # Template for internal bug reports
  - internal_bug_report:
    file: internal_bug_report.md
    labels: [bug]
  # Template for internal feature requests
  - internal_feature_request:
    file: internal_feature_request.md
    labels: [enhancement]
