contact_links:
  - name: PolkaPox
    url: https://github.com/CDCgov/polkapox
    about: Please use the templates to post any issues of feature requests 
templates:
  # Template for bug reports
  - bug_report:
    file: bug_report.md
    labels: [bug]
  # Template for feature requests
  - feature_request:
    file: feature_request.md
    labels: [enhancement]
  
