contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #mpxvassembly channel"
    url: https://nfcore.slack.com/channels/mpxvassembly
    about: Discussion about the nf-core/mpxvassembly pipeline
