name: nf-test

on:
  push:
    branches:
      - dev
      - master
  pull_request:

env:
  NXF_ANSI_LOG: false
  CAPSULE_LOG: none

jobs:

  modules:
    name: Test local modules and subworkflows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v2
        with:
          version: "25.04.0"

      - name: Install nf-test
        uses: nf-core/setup-nf-test@v1
        with:
          version: "0.9.5"

      - name: Run tests
        run: |
          nf-test test \
            modules/local/aggregate_tsvs/tests/main.nf.test \
            modules/local/bwa_denovo/tests/main.nf.test \
            modules/local/graph_reconstruct/tests/main.nf.test \
            modules/local/summarize_qc/tests/main.nf.test \
            modules/local/variant_convert/tests/main.nf.test \
            modules/local/samplesheet_check/tests/main.nf.test \
            modules/local/create_samplesheet/tests/main.nf.test \
            modules/local/samtools_coverage/tests/main.nf.test \
            modules/local/summarize_tsv/tests/main.nf.test \
            modules/local/publish_contigs/tests/main.nf.test \
            modules/local/ivar_consensus_polish_cleanup/tests/main.nf.test \
            subworkflows/local/filter_reads/tests/main.nf.test \
            --profile docker \
            --config tests/nextflow.config \
            --verbose
